language: node_js
node_js:
  - "0.10"
before_install: npm install -g grunt-cli
branches:
  only:
    - master
    - development
    - v2
notifications:
  email:
    - jstrimpel@gmail.com
    - pknepper@walmartlabs.com
