language: node_js
node_js:
  - "0.10"
before_install: npm install -g grunt-cli
branches:
  only:
    - intern
notifications:
  email:
    - jstrimpel@gmail.com
env:
  global:
    - secure: f4PvKBSo7YijgRHIkv0cZcOUzl1dFYd/ooOqZVGiU+GTkI+OttDRodfKHP4xpKvMsh5fkNTEhe6ASiXcUEmHP/nv9yPO2sfVBjkwCY2iz7B/Bn/2+VPLgSs2/W++OYTh++8S0M9cYW2sw/nHs3xeWfj7xpdD5nXeFa8jwJ1oTKc=
    - secure: STMGofHglePPpYTuBd40WpdUQir1GUeczOVtdvde3kaG9M+Sss1ogSCKdLjDj4YnSt4OEvBbBPDohOpECjvL9uF7/1YD8zbllcjwKHz7PblPM42h2KdMisjSK9zXX90hbeQhwd0ZrxSHrypA0owibx6hCxdsB/G6eGJpMGJNJTc=
addons:
  sauce_connect: true